pip install beautifulsoup4
pip install colorama
pip install dacite
pip install lxml
pip install openpyxl
pip install pyperclip
pip install requests
pip install selenium
pip install Unidecode
pip install ytmusicapi
